name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Windows Server
        run: |
          ssh Administrator@192.168.24.246 "powershell.exe -Command `
            cd C:\Users\Ajeigbe Olaoluwa Sam\fastapi-book-project; `
            git fetch --all; `
            git reset --hard origin/main; `
            .\\venv\\Scripts\\activate; `
            pip install -r requirements.txt; `
            Restart-Service -Name fastapi"
