deploy:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact  # ✅ FIXED: Correctly downloading the artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./fastapi-book-project/test

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.WORKFLOW }}" | gh auth login --with-token

      - name: Deploy to Windows Server
        run: |
          gh repo clone olaobey/fastapi-book-project "C:\Users\Ajeigbe Olaoluwa Sam\fastapi-book-project"
          cd "C:\Users\Ajeigbe Olaoluwa Sam\fastapi-book-project"
          git reset --hard origin/main
          call venv\Scripts\activate
          pip install -r requirements.txt
          Restart-Service -Name fastapi
